title: Saion Roy
description: "Postdoctoral Researcher, Northeastern University"
theme: jekyll-theme-minimal

navigation:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications"
  - title: "Talks"
    url: "/talks"
  - title: "CV"
    url: "/cv"
