title: "Saion Roy"
email: sai.roy@northeastern.edu
description: "Postdoctoral Researcher at Northeastern University"
baseurl: ""
url: "https://saionroy.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "main"
