theme: jekyll-theme-minimal
title: "Saion Roy"
description: "Postdoctoral Researcher at Northeastern University"

navigation:
  - title: "Home"
    url: "/"
  - title: "Publications"
    url: "/publications"
  - title: "Talks"
    url: "/talks"
  - title: "CV"
    url: "/cv"
